global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka:8761']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:9000']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8082']

  - job_name: 'sensor-warna-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['sensor-warna-service:8083']

  - job_name: 'sensor-berat-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['sensor-berat-service:8085']

  # BARU: notification-service
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8086']
